version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      MONGO_DB_URI: $MONGO_DB_URI
      SUDO_USER: $SUDO_USER
